# Generated by Django 2.1.4 on 2018-12-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('brower', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('authed', models.BooleanField(default=False)),
            ],
        ),
    ]
