# Generated by Django 2.1.4 on 2018-12-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_request'),
        ('twitter', '0003_auto_20181228_1106'),
    ]

    operations = [
    ]
