# Generated by Django 2.1.4 on 2018-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20181228_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reqer',
            fields=[
                ('ip', models.TextField(primary_key=True, serialize=False)),
                ('badR', models.IntegerField()),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='authed',
        ),
    ]
