# Generated by Django 2.1.4 on 2018-12-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_token'),
        ('twitter', '0006_auto_20181228_1617'),
    ]

    operations = [
    ]
