# Generated by Django 2.1.4 on 2018-12-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_merge_20181228_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqer',
            name='badRA',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reqer',
            name='badR',
            field=models.IntegerField(default=0),
        ),
    ]
