# Generated by Django 2.1.4 on 2018-12-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_auto_20181228_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
