# Generated by Django 2.1.4 on 2018-12-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_loggedinuser'),
        ('twitter', '0009_formtest'),
    ]

    operations = [
    ]
